const CHOSE_DAY = 'CHOSE_DAY';
const CHOSE_ALL_DATE = 'CHOSE_ALL_DATE';
const ADD_ENTRY = 'ADD_ENTRY';
const CHOSE_WEEK_INDEX = 'CHOSE_WEEK_INDEX';
const CHOSE_WEEK_ARR = 'CHOSE_WEEK_ARR';
const ADD_ALL_DAY_MONTH = 'ADD_ALL_DAY_MONTH';
const DELETE_ENTRY = 'DELETE_ENTRY';

export {
  DELETE_ENTRY,
  CHOSE_DAY,
  CHOSE_ALL_DATE,
  ADD_ENTRY,
  CHOSE_WEEK_INDEX,
  CHOSE_WEEK_ARR,
  ADD_ALL_DAY_MONTH
};
